### ISSUE TITLE
As a user I want to register new account

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#1]
1. Main web page of application should contain link to registration form.
2. User should be prompted to provide data:
    * First name
    * Last name
    * E-mail address
    * E-mail address - confirmation
    * Password
    * Password - confirmation
3. User should be INFORMED that real data are prohibited - system will not reported to GIODO and must not contain real persons personal data according to polish law on personal data protection.

Sub-tasks:
- [ ] USERS_DATABASE - create users database
- [ ] USERS_SERVICE - define internal api for creating users
- [ ] USERS_SERVICE - create new user in database
- [ ] WEBSITE_SERVICE - prepare page with registration form 
- [ ] WEBSITE_SERVICE - prepare page with confirmation that user was successfully created, activation needed
- [ ] WEBSITE_SERVICE - prepare page with information that user already exist
- [ ] WEBSITE_SERVICE - prepare page with information that something went wrong
- [ ] WEBSITE_SERVICE - add link to registration form on main page
- [ ] WEBSITE_SERVICE - call internal api of USERS for creating new user
- [ ] API_GATEWAY - define api for requesting registration page
- [ ] API_GATEWAY - create route for requesting registration page
- [ ] API_GATEWAY - define api for creating new user via web page
- [ ] API_GATEWAY - create route for creating new user via web page
