### ISSUE TITLE
As a user I want to recieve an e-mail informing about new account registration

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#2]
1. When user finishes registration process email should be sent to user email address.
2. Email should be sent from address easy to configure on deploy.
3. Email should contain user's account activation link.

Sub-tasks:
- [ ] API_GATEWAY - define api for activation links 
- [ ] EMAIL_SERVICE - define api for requesting sending a registration email
- [ ] EMAIL_SERVICE - send a registration email when requested
- [ ] USERS_SERVICE - call EMAIL_SERVICE api when user is created in database sucessfully. Retry on failure.
