### ISSUE TITLE
As a user I want to confirm my registration by following a link sent by email

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#3]
Issue connected to #2.
User's account should be activated as soon as user confirms registration by clicking the activation link sent him via email after completing the registration process.

Sub-tasks:
- [ ] USERS_SERVICE - define api for activating users
- [ ] USER_SERVICE - change users status to active
- [ ] API_GATEWAY - create route for activating users
