### ISSUE TITLE
As a user I want to recover forgotten password

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#4]
1. On login page there should be link to password recovery form
2. On page user should enter his email address
3. User should get an email with link to password reset
4. On new password page user should provide password twice and submit
5. If account wasn't activated then after password reset it should remain not activated.
6. E-mail confirming password reset should be sent to user

Sub-tasks
- [ ] WEBSITE_SERVICE - on login page add link to password recovery page
- [ ] API gateway - create api and route for request for password recovery page
- [ ] WEBSITE_SERVICE - prepare page for password recovery
- [ ] API gateway - create api and route for request for password recovery for user with specific email
- [ ] WEBSITE_SERVICE - request from USERS_SERVICE password recovery procedure
- [ ] USER_SERVICE - get password reset token from DATABASE
- [ ] USER_SERVICE - invalidate password reset token after 24 hours
- [ ] USER_SERVICE - request EMAIL_SERVICE to send a email with password reset  link and token
- [ ] API gateway - create api and route for request for new password form
- [ ] WEBSITE_SERVICE - prepare page with new password form
- [ ] API gateway - create api and route for request with new password 
- [ ] WEBSITE_SERVICE - send request to USERS_SERVICE to reset password to new one
- [ ] USER_SERVICE - if token match save new password and return status to WEBSITE_SERVICE
- [ ] WEBSITE_SERVICE - prepare process summary page
