### ISSUE TITLE
USERS_SERVICE - serve user details

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#69]
Related to: #7 

Service user should return user details:
- [ ] USERS_SERVICE - define internal api for retrieving user details
- [ ] USERS_SERVICE - implement getting user details from storage
- [ ] USERS_SERVICE - implement serving user details
