### ISSUE TITLE
As a user I want to view my profile

### ISSUE THREAD

**Issue by koikos** [MeetHelp/backlog#7]
1. Web page for logged-in user should contain a link to his profile
2. User should be able to view his (and only his) profile details by following link

Sub-tasks:
- [ ] API_GATEWAY - create route for getting user details
- [ ] USERS_SERVICE - serve user details (#69)
- [ ] WEBSITE_SERVICE - prepare page presenting user details

**Comment by koikos** [comment]
1. Web page for logged-in user should contain a link to his profile
2. User should be able to view his (and only his) profile details by following link

Sub-tasks:
- [ ] API_GATEWAY - create route for getting user details
- [ ] USERS_SERVICE - serve user details (#69)
- [ ] WEBSITE_SERVICE - prepare page presenting user details
